apiVersion: v1
kind: Service
metadata:
  name: bmi-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 3000
  selector:
    component: web        
